-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg64V1h4FdTGObpKzm
KDJ6HMQHWMREHyDEjljkpq8peaegCgYIKoZIzj0DAQehRANCAASzctdZQQhUGNDr
CVW+N48e2C7EobGPJXhcjv8VB9wBJH9p7uTCWWv6LbMu/kH6uF3qjm9zLYaTnIBQ
VUmsdPnO
-----END PRIVATE KEY-----